# IF CONDITION----

# a=50
# is a>10:
# print("a is greater")


# ELSE CONDITION------

# if a>100:
#     print("a is greater")
# else:
#     print("a is less than 100")


# ELSE IF CONDITION ------

# a=50
# b=100
# c=200
# if a>b and a>c:
#     print("a is greater")
# elif b>a and b>c:
#     print("b is greater")
# else:
#     print("c is greater")


# NESTED IF CONDITION------

# a=100
# if a>1000:
#     print("a is greater than 1000")
#     if a>50:
#         print ("a is greater than 50")
#     else:
#         print("a is not greater than 50")
# else:
#     print("a is not greater than 1000")




